const express=require('express');
const router=express.Router();
const orderControllers=require('../controllers/orderController');
router.get('/getAll',orderControllers.getAll);
router.get('/getOrdersByDate',orderControllers.getNOrdersByMonth);
router.get('/getOrderById/:Id',orderControllers.findByUserId);
router.post('/add',orderControllers.add);
router.put('/updateStatus/:Id',orderControllers.updateOrderToDoneById);
router.put('/updateOrder/:Id',orderControllers.updateOrderById);
router.delete('/deleteOrder/:Id',orderControllers.deleteOrder);
module.exports=router;