const express=require('express');
const router=express.Router();
const userControllers=require('../controllers/userController');
router.get('/getAll',userControllers.getAll);
router.get('/findOneById/:Id',userControllers.findOne);
router.post('/findByRole',userControllers.findByRole);
router.post('/login',userControllers.login);
router.post('/register',userControllers.register);
router.delete('/deleteById/:Id',userControllers.deleteUser);
router.put('/updateUser/:Id',userControllers.updateUser);
router.put('/updatePassword/:Id',userControllers.updatePassword);
router.post('/isValidPassword/:Id',userControllers.validPassword);
router.post('/updateEmailAndPass/:Id',userControllers.updateEmailAndPass);
module.exports=router;